language: ruby
sudo: false
rvm:
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
bundler_args: --without development
gemfile:
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - Gemfile
  - gemfiles/rails_head.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
  exclude:
    - rvm: ree
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: ree
      gemfile: Gamfile
    - rvm: 1.9.2
      gemfile: Gamfile
    - rvm: 1.9.3
      gemfile: Gamfile
    - rvm: 2.0.0
      gemfile: Gamfile
    - rvm: 2.1
      gemfile: Gamfile
    - rvm: ree
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_head.gemfile
