name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} with ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - 2.1.9
        - 2.2.10
        - 2.3.8
        - 2.4.10
        - 2.5.8
        - 2.6.6
        - 2.7.2
        - truffleruby-head
        gemfile:
        - gemfiles/rails_3_0.gemfile
        - gemfiles/rails_3_1.gemfile
        - gemfiles/rails_3_2.gemfile
        - gemfiles/rails_4_0.gemfile
        - gemfiles/rails_4_1.gemfile
        - gemfiles/rails_4_2.gemfile
        - gemfiles/rails_5_0.gemfile
        - gemfiles/rails_5_1.gemfile
        - gemfiles/rails_5_2.gemfile
        - gemfiles/rails_6_0.gemfile
        - Gemfile
        - gemfiles/rails_head.gemfile
        exclude:
        - ruby: 1.9.2
          gemfile: gemfiles/rails_4_0.gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_4_1.gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_4_2.gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_5_0.gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_5_1.gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_5_2.gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 1.9.2
          gemfile: Gemfile
        - ruby: 1.9.2
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 1.9.3
          gemfile: gemfiles/rails_5_0.gemfile
        - ruby: 1.9.3
          gemfile: gemfiles/rails_5_1.gemfile
        - ruby: 1.9.3
          gemfile: gemfiles/rails_5_2.gemfile
        - ruby: 1.9.3
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 1.9.3
          gemfile: Gemfile
        - ruby: 1.9.3
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.0.0
          gemfile: gemfiles/rails_5_0.gemfile
        - ruby: 2.0.0
          gemfile: gemfiles/rails_5_1.gemfile
        - ruby: 2.0.0
          gemfile: gemfiles/rails_5_2.gemfile
        - ruby: 2.0.0
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 2.0.0
          gemfile: Gemfile
        - ruby: 2.0.0
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.1.9
          gemfile: gemfiles/rails_5_0.gemfile
        - ruby: 2.1.9
          gemfile: gemfiles/rails_5_1.gemfile
        - ruby: 2.1.9
          gemfile: gemfiles/rails_5_2.gemfile
        - ruby: 2.1.9
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 2.1.9
          gemfile: Gemfile
        - ruby: 2.1.9
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.2.10
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 2.2.10
          gemfile: Gemfile
        - ruby: 2.2.10
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.3.8
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 2.3.8
          gemfile: Gemfile
        - ruby: 2.3.8
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.4.10
          gemfile: gemfiles/rails_6_0.gemfile
        - ruby: 2.4.10
          gemfile: Gemfile
        - ruby: 2.4.10
          gemfile: gemfiles/rails_head.gemfile
        - ruby: 2.5.8
          gemfile: gemfiles/rails_3_0.gemfile
        - ruby: 2.6.6
          gemfile: gemfiles/rails_3_0.gemfile
        - ruby: 2.7.2
          gemfile: gemfiles/rails_3_0.gemfile
        - ruby: 2.7.2
          gemfile: gemfiles/rails_3_1.gemfile
        - ruby: 2.7.2
          gemfile: gemfiles/rails_3_2.gemfile
        - ruby: 2.7.2
          gemfile: gemfiles/rails_4_0.gemfile
        - ruby: 2.7.2
          gemfile: gemfiles/rails_4_1.gemfile
        - ruby: 2.7.2
          gemfile: gemfiles/rails_4_2.gemfile
        - ruby: truffleruby-head
          gemfile: gemfiles/rails_3_0.gemfile
        - ruby: truffleruby-head
          gemfile: gemfiles/rails_3_1.gemfile
        - ruby: truffleruby-head
          gemfile: gemfiles/rails_3_2.gemfile
        - ruby: truffleruby-head
          gemfile: gemfiles/rails_4_0.gemfile
        - ruby: truffleruby-head
          gemfile: gemfiles/rails_4_1.gemfile
        - ruby: truffleruby-head
          gemfile: gemfiles/rails_4_2.gemfile
    env:
      Rails: ${{ matrix.rails }}
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      BUNDLER_VERSION: 1.17.3

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems
    - name: Build and run tests
      run: |
        gem install bundler --version ${{ env.BUNDLER_VERSION }} --no-document
        bundle _${{ env.BUNDLER_VERSION }}_ config path vendor/bundle
        bundle _${{ env.BUNDLER_VERSION }}_ install --jobs 4 --retry 3
        bundle _${{ env.BUNDLER_VERSION }}_ exec rake --trace
